import ToasterContext from "@/components/ToasterContext"
import "../globals.css"
import Provider from "@/components/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="bg-purple-1">
        <Provider>
          <ToasterContext />
          {children}
        </Provider>
       
        </body>
    </html>
  )
}
